# Generated by Django 2.2.4 on 2019-08-19 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PuntosFijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('numero_de_chaleco', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('hora_de_ingreso', models.CharField(blank=True, max_length=300, null=True)),
                ('hora_de_salida', models.CharField(blank=True, max_length=300, null=True)),
                ('novedad', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_de_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_corredor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('hora_de_ingreso', models.CharField(blank=True, max_length=300, null=True)),
                ('hora_de_salida', models.CharField(blank=True, max_length=300, null=True)),
                ('encargado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puntos', models.ManyToManyField(blank=True, to='A3.PuntosFijos')),
            ],
        ),
    ]
