# Generated by Django 2.2.4 on 2019-08-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='institucion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='A3.Institucion'),
            preserve_default=False,
        ),
    ]
