# Generated by Django 2.2.4 on 2019-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0002_corredor_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagen')),
            ],
        ),
    ]
