# Generated by Django 2.2.4 on 2019-08-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0004_tipo_de_corredor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_de_corredor',
            new_name='TipoDeCorredor',
        ),
    ]
