# Generated by Django 2.2.4 on 2019-08-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0006_corredor_tipo_de_corredor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='fecha_de_creacion',
            field=models.DateField(blank=True),
        ),
    ]
