# Generated by Django 2.2.4 on 2019-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0007_auto_20190827_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='hora_de_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='hora_de_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
