# Generated by Django 2.2.4 on 2019-09-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0008_auto_20190827_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodecorredor',
            name='fecha_de_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
