# Generated by Django 2.2.4 on 2019-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0009_tipodecorredor_fecha_de_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='desarrollo_de_la_jornada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='solicitudes',
            field=models.TextField(blank=True),
        ),
    ]
