# Generated by Django 2.2.4 on 2019-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0010_auto_20190914_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentesOcurridos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_inicio', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('ruta', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_del_atendido', models.CharField(blank=True, max_length=200, null=True)),
                ('cc_o_ti_del_atendido', models.CharField(blank=True, max_length=200, null=True)),
                ('genero_atendido', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono_atendido', models.IntegerField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('causa', models.CharField(blank=True, max_length=200, null=True)),
                ('accion_final', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_que_realiza_la_atencion', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_de_final', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivacionesYProyectosRealizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('organizador', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_de_inicio', models.TimeField(blank=True, null=True)),
                ('hora_de_final', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventosRealizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('organizador', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_de_inicio', models.TimeField(blank=True, null=True)),
                ('hora_de_final', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesDeApoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_o_alianza', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar_de_ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_del_apoyo', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_de_llegada', models.TimeField(blank=True, null=True)),
                ('hora_de_retiro', models.TimeField(blank=True, null=True)),
                ('numeral_de_la_unidad_CPS', models.CharField(blank=True, max_length=200, null=True)),
                ('novedades_presentadas', models.TextField(blank=True)),
            ],
        ),
    ]
