# Generated by Django 2.2.4 on 2019-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0013_accidentesocurridos_eps_atendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesocurridos',
            name='edad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='accidentesocurridos',
            name='telefono_atendido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
