# Generated by Django 2.2.4 on 2019-09-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0015_auto_20190915_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesocurridos',
            name='genero_atendido',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('-', 'NA')], max_length=1),
        ),
    ]
