# Generated by Django 2.2.4 on 2019-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0016_auto_20190915_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='accidentes_ocurridos',
            field=models.ManyToManyField(blank=True, to='A3.AccidentesOcurridos'),
        ),
        migrations.AddField(
            model_name='corredor',
            name='activaciones',
            field=models.ManyToManyField(blank=True, to='A3.ActivacionesYProyectosRealizados'),
        ),
        migrations.AddField(
            model_name='corredor',
            name='eventos_realizados',
            field=models.ManyToManyField(blank=True, to='A3.EventosRealizados'),
        ),
        migrations.AddField(
            model_name='corredor',
            name='unidades_de_apoyo',
            field=models.ManyToManyField(blank=True, to='A3.UnidadesDeApoyo'),
        ),
    ]
