# Generated by Django 2.2.4 on 2019-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0017_auto_20190915_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='nombre_del_corredor',
        ),
        migrations.AddField(
            model_name='puntosfijos',
            name='numero_de_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
