# Generated by Django 2.2.4 on 2019-09-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0019_auto_20190915_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesocurridos',
            name='genero_atendido',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('NA', 'NA')], max_length=10),
        ),
    ]
