# Generated by Django 2.2.4 on 2019-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0020_auto_20190915_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesSolicitadasOtrasInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('novedad', models.CharField(blank=True, max_length=200, null=True)),
                ('guardia_que_solicita', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_de_solicitud', models.TimeField(blank=True, null=True)),
                ('hora_de_atencion', models.TimeField(blank=True, null=True)),
                ('numeral_unidad', models.CharField(blank=True, max_length=200, null=True)),
                ('n_movil_o_placa', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('accion_final', models.TextField(blank=True)),
            ],
        ),
    ]
