# Generated by Django 2.2.4 on 2019-09-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0021_unidadessolicitadasotrasinst'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='unidades_solicitada_otras_inst',
            field=models.ManyToManyField(blank=True, to='A3.UnidadesSolicitadasOtrasInst'),
        ),
    ]
