# Generated by Django 2.2.5 on 2019-09-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0022_corredor_unidades_solicitada_otras_inst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='puntos',
        ),
    ]
