# Generated by Django 2.2.5 on 2019-09-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0023_remove_corredor_puntos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuntosFijos',
            new_name='Guardianes',
        ),
    ]
