# Generated by Django 2.2.5 on 2019-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0024_auto_20190916_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='guardianes',
            field=models.ManyToManyField(blank=True, to='A3.Guardianes'),
        ),
    ]
