# Generated by Django 2.2.5 on 2019-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0025_corredor_guardianes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianes',
            old_name='hora_de_ingreso',
            new_name='acciones_tomadas',
        ),
        migrations.RenameField(
            model_name='guardianes',
            old_name='numero_de_chaleco',
            new_name='numero_de_contrato',
        ),
        migrations.RemoveField(
            model_name='guardianes',
            name='hora_de_salida',
        ),
        migrations.AddField(
            model_name='guardianes',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianes',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianes',
            name='inasistio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianes',
            name='retarda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardianes',
            name='novedad',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
