# Generated by Django 2.2.5 on 2019-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A3', '0026_auto_20190916_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianes',
            old_name='retarda',
            new_name='retardo',
        ),
    ]
